### PR TITLE
Fixed carousel

### PR DESCRIPTION
**Pull request by mrrehwaldt**
This one has a working carousel.

### CODE REVIEW

**Comment by Annijah** [comment]
A comment

**Comment by VinnySmith** [comment]
Cool I left a comment

**Comment by VinnySmith** [comment]
I left another comment

**Comment by Liz-ard** [comment]
C o m m e n t

**Comment by DamianMrozowski** [comment]
Comment

**Comment by EthanDiller** [comment]
Yo

**Comment by Liz-ard** [comment]
A e St HE ti c

**Comment by CSstudent1** [comment]
lol

**Pull request merged**
